//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;

using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Mapping;

using VTQT.Core.Domain.Apps;
using VTQT.Core.Domain.Localization;

namespace VTQT.Core.Domain.Dashboard
{
	/// <summary>
	/// Database       : Dashboard
	/// Data Source    : 192.168.100.73
	/// Server Version : 8.0.28-0ubuntu0.20.04.3
	/// </summary>
	public partial class DashboardDataConnection : LinqToDB.Data.DataConnection
	{
		public ITable<AuthorizeFile>    AuthorizeFiles   { get { return this.GetTable<AuthorizeFile>(); } }
		public ITable<AuthorizeToRole>  AuthorizeToRoles { get { return this.GetTable<AuthorizeToRole>(); } }
		public ITable<DashBoardUser>    DashBoardUsers   { get { return this.GetTable<DashBoardUser>(); } }
		public ITable<Example>          Examples         { get { return this.GetTable<Example>(); } }
		public ITable<FTTH>             Ftths            { get { return this.GetTable<FTTH>(); } }
		public ITable<FTTH2022>         FTTH2022         { get { return this.GetTable<FTTH2022>(); } }
		public ITable<FTTHMB3132022>    FTTHMB3132022    { get { return this.GetTable<FTTHMB3132022>(); } }
		public ITable<FTTHMBFINAL>      Ftthmbfinals     { get { return this.GetTable<FTTHMBFINAL>(); } }
		public ITable<MasterFileKH2022> MasterFileKH2022 { get { return this.GetTable<MasterFileKH2022>(); } }
		public ITable<MasterVTCNTT>     MasterVtcntts    { get { return this.GetTable<MasterVTCNTT>(); } }
		public ITable<NameTableExist>   NameTableExists  { get { return this.GetTable<NameTableExist>(); } }
		public ITable<Report>           Reports          { get { return this.GetTable<Report>(); } }
		public ITable<ReportGroup>      ReportGroups     { get { return this.GetTable<ReportGroup>(); } }
		public ITable<RosePrice>        RosePrices       { get { return this.GetTable<RosePrice>(); } }
		public ITable<SelectTable>      SelectTables     { get { return this.GetTable<SelectTable>(); } }
		/// <summary>
		/// Danh mục Dữ liệu
		/// </summary>
		public ITable<StorageValue>     StorageValues    { get { return this.GetTable<StorageValue>(); } }
		/// <summary>
		/// Danh mục loại dữ liệu
		/// </summary>
		public ITable<TypeValue>        TypeValues       { get { return this.GetTable<TypeValue>(); } }
		/// <summary>
		/// VIEW
		/// </summary>
		public ITable<view2>            view2            { get { return this.GetTable<view2>(); } }

		public DashboardDataConnection()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public DashboardDataConnection(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public DashboardDataConnection(LinqToDbConnectionOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public DashboardDataConnection(LinqToDbConnectionOptions<DashboardDataConnection> options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Serializable]
	[Table("AuthorizeFile")]
	public partial class AuthorizeFile : BaseEntity
	{
		[Column, NotNull    ] public string AuthorizedId  { get; set; } // varchar(255)
		[Column, NotNull    ] public string DelegatorId   { get; set; } // varchar(255)
		[Column,    Nullable] public string Name          { get; set; } // varchar(50)
		[Column,    Nullable] public string NameAuthorize { get; set; } // varchar(255)
		[Column, NotNull    ] public string FileId        { get; set; } // varchar(255)
		[Column,    Nullable] public string NameFile      { get; set; } // varchar(255)
	}

	[Serializable]
	[Table("AuthorizeToRole")]
	public partial class AuthorizeToRole : BaseEntity
	{
		[Column,    Nullable] public string    DelegatorId          { get; set; } // varchar(255)
		[Column, NotNull    ] public string    AuthorizedId         { get; set; } // varchar(255)
		[Column,    Nullable] public string    ListFileAuthorizedId { get; set; } // varchar(255)
		[Column,    Nullable] public DateTime? CreateDate           { get; set; } // datetime
		[Column, NotNull    ] public string    TypeValueId          { get; set; } // varchar(255)
		[Column,    Nullable] public string    Name                 { get; set; } // varchar(50)
		[Column,    Nullable] public string    NameAuthorize        { get; set; } // varchar(255)
		[Column,    Nullable] public string    ListNameFile         { get; set; } // varchar(255)
		[Column,    Nullable] public string    NameTypeValue        { get; set; } // varchar(255)
	}

	[Serializable]
	[Table("DashBoardUser")]
	public partial class DashBoardUser : BaseEntity
	{
		[Column, NotNull    ] public string   TypeValueId { get; set; } // varchar(255)
		[Column, NotNull    ] public string   UserId      { get; set; } // varchar(255)
		[Column, NotNull    ] public DateTime CreatedDate { get; set; } // datetime
		[Column,    Nullable] public string   CreatedBy   { get; set; } // varchar(255)
	}

	[Serializable]
	[Table("Example")]
	public partial class Example : BaseEntity
	{
		[Column,    Nullable] public string    Name        { get; set; } // varchar(50)
		[Column,    Nullable] public int?      NumOne      { get; set; } // int
		[Column,    Nullable] public int?      NumTwo      { get; set; } // int
		[Column,    Nullable] public int?      NumSum      { get; set; } // int
		[Column,    Nullable] public DateTime? DateExample { get; set; } // date
	}

	[Serializable]
	[Table("FTTH")]
	public partial class FTTH : BaseEntity
	{
		[Column("Tuần cập nhật"),                                           Nullable] public string TuầnCậpNhật                               { get; set; } // varchar(50)
		[Column(),                                                          Nullable] public string Miền                                      { get; set; } // varchar(50)
		[Column("Tỉnh thành"),                                              Nullable] public string TỉnhThành                                 { get; set; } // varchar(50)
		[Column("Năm\nhợp đồng"),                                           Nullable] public string Năm_hợpĐồng                               { get; set; } // varchar(50)
		[Column("Tên dự án"),                                               Nullable] public string TênDựÁn                                   { get; set; } // varchar(50)
		[Column("Tình trạng hoạt động"),                                    Nullable] public string TìnhTrạngHoạtĐộng                         { get; set; } // varchar(50)
		[Column("Loại khách hàng"),                                         Nullable] public string LoạiKháchHàng                             { get; set; } // varchar(50)
		[Column("Khách hàng"),                                              Nullable] public string KháchHàng                                 { get; set; } // varchar(100)
		[Column("Số điện thoại"),                                           Nullable] public string SốĐiệnThoại                               { get; set; } // varchar(150)
		[Column("Địa chỉ"),                                                 Nullable] public string ĐịaChỉ                                    { get; set; } // varchar(150)
		[Column("Mã KH/CID"),                                               Nullable] public string MãKH_CID                                  { get; set; } // varchar(50)
		[Column("Số Hợp đồng"),                                             Nullable] public string SốHợpĐồng                                 { get; set; } // varchar(100)
		[Column("CS Phụ trách"),                                            Nullable] public string CSPhụTrách                                { get; set; } // varchar(50)
		[Column("Gói cước"),                                                Nullable] public string GóiCước                                   { get; set; } // varchar(50)
		[Column("Trả trước"),                                               Nullable] public string TrảTrước                                  { get; set; } // varchar(50)
		[Column("Số tháng được tặng trong 1 năm"),                          Nullable] public string SốThángĐượcTặngTrong1Năm                  { get; set; } // varchar(50)
		[Column("Số tháng dùng"),                                           Nullable] public string SốThángDùng                               { get; set; } // varchar(50)
		[Column("Cước hợp đồng hàng tháng"),                                Nullable] public string CướcHợpĐồngHàngTháng                      { get; set; } // varchar(50)
		[Column("Cước tháng Internet"),                                     Nullable] public string CướcThángInternet                         { get; set; } // varchar(50)
		[Column("Cước tháng truyền hình"),                                  Nullable] public string CướcThángTruyềnHình                       { get; set; } // varchar(50)
		[Column("Tỷ lệ chia sẻ cho đối tác phần Internet"),                 Nullable] public string TỷLệChiaSẻChoĐốiTácPhầnInternet           { get; set; } // varchar(255)
		[Column("Tỷ lệ chia sẻ cho đối tác phần truyền hình"),              Nullable] public string TỷLệChiaSẻChoĐốiTácPhầnTruyềnHình         { get; set; } // varchar(50)
		[Column("Cước HTC được nhận hàng tháng"),                           Nullable] public string CướcHTCĐượcNhậnHàngTháng                  { get; set; } // varchar(50)
		[Column("Cước HTC được nhận được TB sau khi trừ đi khuyến mại"),    Nullable] public string CướcHTCĐượcNhậnĐượcTBSauKhiTrừĐiKhuyếnMại { get; set; } // varchar(255)
		[Column("Cước đã thu lần 1"),                                       Nullable] public string CướcĐãThuLần1                             { get; set; } // varchar(50)
		[Column("Chủ thể xuất hóa đơn"),                                    Nullable] public string ChủThểXuấtHóaĐơn                          { get; set; } // varchar(50)
		[Column("Ngày ký HĐ/ lắp đặt"),                                     Nullable] public string NgàyKýHĐ_LắpĐặt                           { get; set; } // varchar(50)
		[Column("Ngày nghiệm thu"),                                         Nullable] public string NgàyNghiệmThu                             { get; set; } // varchar(50)
		[Column("Ngày hết hạn theo term 12 tháng"),                         Nullable] public string NgàyHếtHạnTheoTerm12Tháng                 { get; set; } // varchar(50)
		[Column("Ngày thanh lý"),                                           Nullable] public string NgàyThanhLý                               { get; set; } // varchar(50)
		[Column("Thanh lý (trước hạn hay sau hạn)"),                        Nullable] public string ThanhLý_trướcHạnHaySauHạn_                { get; set; } // varchar(50)
		[Column("Doanh thu mất đi do thanh lý (theo term HĐ)"),             Nullable] public string DoanhThuMấtĐiDoThanhLý_theoTermHĐ_        { get; set; } // varchar(50)
		[Column("Chi tiết lý do thanh lý"),                                 Nullable] public string ChiTiếtLýDoThanhLý                        { get; set; } // varchar(50)
		[Column("Phân loại thanh lý"),                                      Nullable] public string PhânLoạiThanhLý                           { get; set; } // varchar(50)
		[Column(),                                                          Nullable] public string Nền                                       { get; set; } // varchar(50)
		[Column("Giảm nền"),                                                Nullable] public string GiảmNền                                   { get; set; } // varchar(50)
		[Column("Doanh thu phát triển mới"),                                Nullable] public string DoanhThuPhátTriểnMới                      { get; set; } // varchar(255)
		[Column("Tổng DT"),                                                 Nullable] public string TổngDT                                    { get; set; } // varchar(50)
		[Column("Tháng 1"),                                                 Nullable] public string Tháng1                                    { get; set; } // varchar(50)
		[Column("Tháng 2"),                                                 Nullable] public string Tháng2                                    { get; set; } // varchar(50)
		[Column("Tháng 3"),                                                 Nullable] public string Tháng3                                    { get; set; } // varchar(50)
		[Column("Tháng 4"),                                                 Nullable] public string Tháng4                                    { get; set; } // varchar(50)
		[Column("Tháng 5"),                                                 Nullable] public string Tháng5                                    { get; set; } // varchar(50)
		[Column("Tháng 6"),                                                 Nullable] public string Tháng6                                    { get; set; } // varchar(50)
		[Column("Tháng 7"),                                                 Nullable] public string Tháng7                                    { get; set; } // varchar(50)
		[Column("Tháng 8"),                                                 Nullable] public string Tháng8                                    { get; set; } // varchar(50)
		[Column("Tháng 9"),                                                 Nullable] public string Tháng9                                    { get; set; } // varchar(50)
		[Column("Tháng 10"),                                                Nullable] public string Tháng10                                   { get; set; } // varchar(50)
		[Column("Tháng 11"),                                                Nullable] public string Tháng11                                   { get; set; } // varchar(50)
		[Column("Tháng 12"),                                                Nullable] public string Tháng12                                   { get; set; } // varchar(50)
		[Column("Ghi chú"),                                                 Nullable] public string GhiChú                                    { get; set; } // varchar(50)
	}

	[Serializable]
	[Table("FTTH2022")]
	public partial class FTTH2022 : BaseEntity
	{
		[Column("Tuần cập nhật"),                                           Nullable] public string TuầnCậpNhật                               { get; set; } // varchar(50)
		[Column(),                                                          Nullable] public string Miền                                      { get; set; } // varchar(50)
		[Column("Tỉnh thành"),                                              Nullable] public string TỉnhThành                                 { get; set; } // varchar(50)
		[Column("Năm\nhợp đồng"),                                           Nullable] public string Năm_hợpĐồng                               { get; set; } // varchar(50)
		[Column("Tên dự án"),                                               Nullable] public string TênDựÁn                                   { get; set; } // varchar(50)
		[Column("Tình trạng hoạt động"),                                    Nullable] public string TìnhTrạngHoạtĐộng                         { get; set; } // varchar(50)
		[Column("Loại khách hàng"),                                         Nullable] public string LoạiKháchHàng                             { get; set; } // varchar(50)
		[Column("Khách hàng"),                                              Nullable] public string KháchHàng                                 { get; set; } // varchar(100)
		[Column("Số điện thoại"),                                           Nullable] public string SốĐiệnThoại                               { get; set; } // varchar(150)
		[Column("Địa chỉ"),                                                 Nullable] public string ĐịaChỉ                                    { get; set; } // varchar(150)
		[Column("Mã KH/CID"),                                               Nullable] public string MãKH_CID                                  { get; set; } // varchar(50)
		[Column("Số Hợp đồng"),                                             Nullable] public string SốHợpĐồng                                 { get; set; } // varchar(100)
		[Column("CS Phụ trách"),                                            Nullable] public string CSPhụTrách                                { get; set; } // varchar(50)
		[Column("Sale phụ trách"),                                          Nullable] public string SalePhụTrách                              { get; set; } // varchar(50)
		[Column("Gói cước"),                                                Nullable] public string GóiCước                                   { get; set; } // varchar(50)
		[Column("Trả trước"),                                               Nullable] public string TrảTrước                                  { get; set; } // varchar(50)
		[Column("Số tháng được tặng trong 1 năm"),                          Nullable] public string SốThángĐượcTặngTrong1Năm                  { get; set; } // varchar(50)
		[Column("Số tháng dùng"),                                           Nullable] public string SốThángDùng                               { get; set; } // varchar(50)
		[Column("Cước hợp đồng hàng tháng"),                                Nullable] public string CướcHợpĐồngHàngTháng                      { get; set; } // varchar(50)
		[Column("Cước tháng Internet"),                                     Nullable] public string CướcThángInternet                         { get; set; } // varchar(50)
		[Column("Cước tháng truyền hình"),                                  Nullable] public string CướcThángTruyềnHình                       { get; set; } // varchar(50)
		[Column("Tỷ lệ chia sẻ cho đối tác phần Internet"),                 Nullable] public string TỷLệChiaSẻChoĐốiTácPhầnInternet           { get; set; } // varchar(50)
		[Column("Tỷ lệ chia sẻ cho đối tác phần truyền hình"),              Nullable] public string TỷLệChiaSẻChoĐốiTácPhầnTruyềnHình         { get; set; } // varchar(50)
		[Column("Cước HTC được nhận hàng tháng"),                           Nullable] public string CướcHTCĐượcNhậnHàngTháng                  { get; set; } // varchar(50)
		[Column("Cước HTC được nhận được TB sau khi trừ đi khuyến mại"),    Nullable] public string CướcHTCĐượcNhậnĐượcTBSauKhiTrừĐiKhuyếnMại { get; set; } // varchar(255)
		[Column("Cước đã thu lần 1"),                                       Nullable] public string CướcĐãThuLần1                             { get; set; } // varchar(50)
		[Column("Chủ thể xuất hóa đơn"),                                    Nullable] public string ChủThểXuấtHóaĐơn                          { get; set; } // varchar(50)
		[Column("Ngày ký HĐ/ lắp đặt"),                                     Nullable] public string NgàyKýHĐ_LắpĐặt                           { get; set; } // varchar(50)
		[Column("Ngày nghiệm thu"),                                         Nullable] public string NgàyNghiệmThu                             { get; set; } // varchar(50)
		[Column("Ngày hết hạn theo term 12 tháng"),                         Nullable] public string NgàyHếtHạnTheoTerm12Tháng                 { get; set; } // varchar(50)
		[Column("Ngày thanh lý"),                                           Nullable] public string NgàyThanhLý                               { get; set; } // varchar(50)
		[Column("Thanh lý (trước hạn hay sau hạn)"),                        Nullable] public string ThanhLý_trướcHạnHaySauHạn_                { get; set; } // varchar(50)
		[Column("Doanh thu mất đi do thanh lý (theo term HĐ)"),             Nullable] public string DoanhThuMấtĐiDoThanhLý_theoTermHĐ_        { get; set; } // varchar(50)
		[Column("Chi tiết lý do thanh lý"),                                 Nullable] public string ChiTiếtLýDoThanhLý                        { get; set; } // varchar(100)
		[Column("Phân loại thanh lý"),                                      Nullable] public string PhânLoạiThanhLý                           { get; set; } // varchar(100)
		[Column(),                                                          Nullable] public string Nền                                       { get; set; } // varchar(255)
		[Column("Giảm nền"),                                                Nullable] public string GiảmNền                                   { get; set; } // varchar(255)
		[Column("Doanh thu phát triển mới"),                                Nullable] public string DoanhThuPhátTriểnMới                      { get; set; } // varchar(255)
		[Column("Tổng DT"),                                                 Nullable] public string TổngDT                                    { get; set; } // varchar(255)
		[Column("Tháng 1"),                                                 Nullable] public string Tháng1                                    { get; set; } // varchar(255)
		[Column("Tháng 2"),                                                 Nullable] public string Tháng2                                    { get; set; } // varchar(255)
		[Column("Tháng 3"),                                                 Nullable] public string Tháng3                                    { get; set; } // varchar(255)
		[Column("Tháng 4"),                                                 Nullable] public string Tháng4                                    { get; set; } // varchar(255)
		[Column("Tháng 5"),                                                 Nullable] public string Tháng5                                    { get; set; } // varchar(255)
		[Column("Tháng 6"),                                                 Nullable] public string Tháng6                                    { get; set; } // varchar(255)
		[Column("Tháng 7"),                                                 Nullable] public string Tháng7                                    { get; set; } // varchar(255)
		[Column("Tháng 8"),                                                 Nullable] public string Tháng8                                    { get; set; } // varchar(255)
		[Column("Tháng 9"),                                                 Nullable] public string Tháng9                                    { get; set; } // varchar(255)
		[Column("Tháng 10"),                                                Nullable] public string Tháng10                                   { get; set; } // varchar(255)
		[Column("Tháng 11"),                                                Nullable] public string Tháng11                                   { get; set; } // varchar(255)
		[Column("Tháng 12"),                                                Nullable] public string Tháng12                                   { get; set; } // varchar(255)
		[Column("Ghi chú"),                                                 Nullable] public string GhiChú                                    { get; set; } // varchar(50)
	}

	[Serializable]
	[Table("FTTHMB3132022")]
	public partial class FTTHMB3132022 : BaseEntity
	{
		[Column("Tuần cập nhật"),                                           Nullable] public string TuầnCậpNhật                               { get; set; } // varchar(50)
		[Column(),                                                          Nullable] public string Miền                                      { get; set; } // varchar(50)
		[Column("Tỉnh thành"),                                              Nullable] public string TỉnhThành                                 { get; set; } // varchar(50)
		[Column("Năm\nhợp đồng"),                                           Nullable] public string Năm_hợpĐồng                               { get; set; } // varchar(50)
		[Column("Tên dự án"),                                               Nullable] public string TênDựÁn                                   { get; set; } // varchar(50)
		[Column("Tình trạng hoạt động"),                                    Nullable] public string TìnhTrạngHoạtĐộng                         { get; set; } // varchar(50)
		[Column("Loại khách hàng"),                                         Nullable] public string LoạiKháchHàng                             { get; set; } // varchar(50)
		[Column("Khách hàng"),                                              Nullable] public string KháchHàng                                 { get; set; } // varchar(100)
		[Column("Số điện thoại"),                                           Nullable] public string SốĐiệnThoại                               { get; set; } // varchar(150)
		[Column("Địa chỉ"),                                                 Nullable] public string ĐịaChỉ                                    { get; set; } // varchar(150)
		[Column("Mã KH/CID"),                                               Nullable] public string MãKH_CID                                  { get; set; } // varchar(50)
		[Column("Số Hợp đồng"),                                             Nullable] public string SốHợpĐồng                                 { get; set; } // varchar(100)
		[Column("CS Phụ trách"),                                            Nullable] public string CSPhụTrách                                { get; set; } // varchar(50)
		[Column("Sale phụ trách"),                                          Nullable] public string SalePhụTrách                              { get; set; } // varchar(50)
		[Column("Gói cước"),                                                Nullable] public string GóiCước                                   { get; set; } // varchar(50)
		[Column("Trả trước"),                                               Nullable] public string TrảTrước                                  { get; set; } // varchar(50)
		[Column("Số tháng được tặng trong 1 năm"),                          Nullable] public string SốThángĐượcTặngTrong1Năm                  { get; set; } // varchar(50)
		[Column("Số tháng dùng"),                                           Nullable] public string SốThángDùng                               { get; set; } // varchar(50)
		[Column("Cước hợp đồng hàng tháng"),                                Nullable] public string CướcHợpĐồngHàngTháng                      { get; set; } // varchar(50)
		[Column("Cước tháng Internet"),                                     Nullable] public string CướcThángInternet                         { get; set; } // varchar(50)
		[Column("Cước tháng truyền hình"),                                  Nullable] public string CướcThángTruyềnHình                       { get; set; } // varchar(50)
		[Column("Cước HTC được nhận hàng tháng"),                           Nullable] public string CướcHTCĐượcNhậnHàngTháng                  { get; set; } // varchar(50)
		[Column("Cước HTC được nhận được TB sau khi trừ đi khuyến mại"),    Nullable] public string CướcHTCĐượcNhậnĐượcTBSauKhiTrừĐiKhuyếnMại { get; set; } // varchar(255)
		[Column("Cước đã thu lần 1"),                                       Nullable] public string CướcĐãThuLần1                             { get; set; } // varchar(50)
		[Column("Ngày ký HĐ/ lắp đặt"),                                     Nullable] public string NgàyKýHĐ_LắpĐặt                           { get; set; } // varchar(50)
		[Column("Ngày nghiệm thu"),                                         Nullable] public string NgàyNghiệmThu                             { get; set; } // varchar(50)
		[Column("Ngày hết hạn theo term 12 tháng"),                         Nullable] public string NgàyHếtHạnTheoTerm12Tháng                 { get; set; } // varchar(50)
		[Column("Ngày thanh lý"),                                           Nullable] public string NgàyThanhLý                               { get; set; } // varchar(50)
		[Column("Thanh lý (trước hạn hay sau hạn)"),                        Nullable] public string ThanhLý_trướcHạnHaySauHạn_                { get; set; } // varchar(50)
		[Column("Doanh thu mất đi do thanh lý (theo term HĐ)"),             Nullable] public string DoanhThuMấtĐiDoThanhLý_theoTermHĐ_        { get; set; } // varchar(50)
		[Column("Chi tiết lý do thanh lý"),                                 Nullable] public string ChiTiếtLýDoThanhLý                        { get; set; } // varchar(100)
		[Column("Phân loại thanh lý"),                                      Nullable] public string PhânLoạiThanhLý                           { get; set; } // varchar(50)
		[Column(),                                                          Nullable] public string Nền                                       { get; set; } // varchar(50)
		[Column("Giảm nền"),                                                Nullable] public string GiảmNền                                   { get; set; } // varchar(50)
		[Column("Doanh thu phát triển mới"),                                Nullable] public string DoanhThuPhátTriểnMới                      { get; set; } // varchar(50)
		[Column("Tổng DT"),                                                 Nullable] public string TổngDT                                    { get; set; } // varchar(50)
		[Column(),                                                          Nullable] public string Column1                                   { get; set; } // varchar(50)
		[Column(),                                                          Nullable] public string Column2                                   { get; set; } // varchar(50)
		[Column("Tháng 3"),                                                 Nullable] public string Tháng3                                    { get; set; } // varchar(50)
		[Column("Tháng 4"),                                                 Nullable] public string Tháng4                                    { get; set; } // varchar(50)
		[Column(),                                                          Nullable] public string Tháng5                                    { get; set; } // varchar(50)
		[Column(),                                                          Nullable] public string Tháng6                                    { get; set; } // varchar(50)
		[Column(),                                                          Nullable] public string Tháng7                                    { get; set; } // varchar(50)
		[Column(),                                                          Nullable] public string Tháng8                                    { get; set; } // varchar(50)
		[Column(),                                                          Nullable] public string Tháng9                                    { get; set; } // varchar(50)
		[Column(),                                                          Nullable] public string Tháng10                                   { get; set; } // varchar(50)
		[Column("Tháng 11"),                                                Nullable] public string Tháng11                                   { get; set; } // varchar(50)
		[Column("Tháng 12"),                                                Nullable] public string Tháng12                                   { get; set; } // varchar(50)
	}

	[Serializable]
	[Table("FTTHMBFINAL")]
	public partial class FTTHMBFINAL : BaseEntity
	{
		[Column("Tuần cập nhật"),                                        Nullable] public string TuầnCậpNhật                               { get; set; } // varchar(50)
		[Column(),                                                       Nullable] public string Miền                                      { get; set; } // varchar(50)
		[Column("Tỉnh thành"),                                           Nullable] public string TỉnhThành                                 { get; set; } // varchar(50)
		[Column("Năm\nhợp đồng"),                                        Nullable] public string Năm_hợpĐồng                               { get; set; } // varchar(50)
		[Column("Tên dự án"),                                            Nullable] public string TênDựÁn                                   { get; set; } // varchar(50)
		[Column("Tình trạng hoạt động"),                                 Nullable] public string TìnhTrạngHoạtĐộng                         { get; set; } // varchar(50)
		[Column("Loại khách hàng"),                                      Nullable] public string LoạiKháchHàng                             { get; set; } // varchar(50)
		[Column("Khách hàng"),                                           Nullable] public string KháchHàng                                 { get; set; } // varchar(150)
		[Column("Số điện thoại"),                                        Nullable] public string SốĐiệnThoại                               { get; set; } // varchar(150)
		[Column("Địa chỉ"),                                              Nullable] public string ĐịaChỉ                                    { get; set; } // varchar(150)
		[Column("Mã KH/CID"),                                            Nullable] public string MãKH_CID                                  { get; set; } // varchar(50)
		[Column("Số Hợp đồng"),                                          Nullable] public string SốHợpĐồng                                 { get; set; } // varchar(100)
		[Column("CS Phụ trách"),                                         Nullable] public string CSPhụTrách                                { get; set; } // varchar(50)
		[Column("Gói cước"),                                             Nullable] public string GóiCước                                   { get; set; } // varchar(50)
		[Column("Trả trước"),                                            Nullable] public string TrảTrước                                  { get; set; } // varchar(50)
		[Column("Số tháng được tặng trong 1 năm"),                       Nullable] public string SốThángĐượcTặngTrong1Năm                  { get; set; } // varchar(50)
		[Column("Số tháng dùng"),                                        Nullable] public string SốThángDùng                               { get; set; } // varchar(50)
		[Column("Cước hợp đồng hàng tháng"),                             Nullable] public string CướcHợpĐồngHàngTháng                      { get; set; } // varchar(255)
		[Column("Cước tháng Internet"),                                  Nullable] public string CướcThángInternet                         { get; set; } // varchar(255)
		[Column("Cước tháng truyền hình"),                               Nullable] public string CướcThángTruyềnHình                       { get; set; } // varchar(255)
		[Column("Tỷ lệ chia sẻ cho đối tác phần Internet"),              Nullable] public string TỷLệChiaSẻChoĐốiTácPhầnInternet           { get; set; } // varchar(255)
		[Column("Tỷ lệ chia sẻ cho đối tác phần truyền hình"),           Nullable] public string TỷLệChiaSẻChoĐốiTácPhầnTruyềnHình         { get; set; } // varchar(255)
		[Column("Cước HTC được nhận hàng tháng"),                        Nullable] public string CướcHTCĐượcNhậnHàngTháng                  { get; set; } // varchar(255)
		[Column("Cước HTC được nhận được TB sau khi trừ đi khuyến mại"), Nullable] public string CướcHTCĐượcNhậnĐượcTBSauKhiTrừĐiKhuyếnMại { get; set; } // varchar(255)
		[Column("Cước đã thu lần 1"),                                    Nullable] public string CướcĐãThuLần1                             { get; set; } // varchar(255)
		[Column("Chủ thể xuất hóa đơn"),                                 Nullable] public string ChủThểXuấtHóaĐơn                          { get; set; } // varchar(50)
		[Column("Ngày ký HĐ/ lắp đặt"),                                  Nullable] public string NgàyKýHĐ_LắpĐặt                           { get; set; } // varchar(50)
		[Column("Ngày nghiệm thu"),                                      Nullable] public string NgàyNghiệmThu                             { get; set; } // varchar(50)
		[Column("Ngày hết hạn theo term 12 tháng"),                      Nullable] public string NgàyHếtHạnTheoTerm12Tháng                 { get; set; } // varchar(50)
		[Column("Ngày thanh lý"),                                        Nullable] public string NgàyThanhLý                               { get; set; } // varchar(50)
		[Column("Thanh lý (trước hạn hay sau hạn)"),                     Nullable] public string ThanhLý_trướcHạnHaySauHạn_                { get; set; } // varchar(50)
		[Column("Doanh thu mất đi do thanh lý (theo term HĐ)"),          Nullable] public string DoanhThuMấtĐiDoThanhLý_theoTermHĐ_        { get; set; } // varchar(50)
		[Column("Chi tiết lý do thanh lý"),                              Nullable] public string ChiTiếtLýDoThanhLý                        { get; set; } // varchar(50)
		[Column("Phân loại thanh lý"),                                   Nullable] public string PhânLoạiThanhLý                           { get; set; } // varchar(50)
		[Column("Nền 2021"),                                             Nullable] public string Nền2021                                   { get; set; } // varchar(50)
		[Column("Giảm nền 2021"),                                        Nullable] public string GiảmNền2021                               { get; set; } // varchar(50)
		[Column("Doanh thu phát triển mới"),                             Nullable] public string DoanhThuPhátTriểnMới                      { get; set; } // varchar(50)
		[Column("Tổng DT 2021"),                                         Nullable] public string TổngDT2021                                { get; set; } // varchar(50)
		[Column("Tháng 1"),                                              Nullable] public string Tháng1                                    { get; set; } // varchar(50)
		[Column("Tháng 2"),                                              Nullable] public string Tháng2                                    { get; set; } // varchar(50)
		[Column("Tháng 3"),                                              Nullable] public string Tháng3                                    { get; set; } // varchar(50)
		[Column("Tháng 4"),                                              Nullable] public string Tháng4                                    { get; set; } // varchar(50)
		[Column("Tháng 5"),                                              Nullable] public string Tháng5                                    { get; set; } // varchar(255)
		[Column("Tháng 6"),                                              Nullable] public string Tháng6                                    { get; set; } // varchar(255)
		[Column("Tháng 7"),                                              Nullable] public string Tháng7                                    { get; set; } // varchar(255)
		[Column("Tháng 8"),                                              Nullable] public string Tháng8                                    { get; set; } // varchar(255)
		[Column("Tháng 9"),                                              Nullable] public string Tháng9                                    { get; set; } // varchar(255)
		[Column("Tháng 10"),                                             Nullable] public string Tháng10                                   { get; set; } // varchar(255)
		[Column("Tháng 11"),                                             Nullable] public string Tháng11                                   { get; set; } // varchar(255)
		[Column("Tháng 12"),                                             Nullable] public string Tháng12                                   { get; set; } // varchar(255)
		[Column("Ghi chú"),                                              Nullable] public string GhiChú                                    { get; set; } // varchar(50)
	}

	[Serializable]
	[Table("MasterFileKH2022")]
	public partial class MasterFileKH2022 : BaseEntity
	{
		[Column("Tuần báo cáo"),                                               Nullable] public string TuầnBáoCáo                                     { get; set; } // varchar(50)
		[Column("KH nền -0 hay mới - 1"),                                      Nullable] public int?   KHNền_0HayMới_1                                { get; set; } // int
		[Column("Qua đại lý/ KH cuối"),                                        Nullable] public string QuaĐạiLý_KHCuối                                { get; set; } // varchar(50)
		[Column("Khu vực"),                                                    Nullable] public string KhuVực                                         { get; set; } // varchar(50)
		[Column("Danh mục khách hàng"),                                        Nullable] public string DanhMụcKháchHàng                               { get; set; } // varchar(50)
		[Column("Nhóm khách hàng"),                                            Nullable] public string NhómKháchHàng                                  { get; set; } // varchar(50)
		[Column("Loại hình cơ cấu Kh"),                                        Nullable] public string LoạiHìnhCơCấuKh                                { get; set; } // varchar(50)
		[Column("Kiểu Khách hàng"),                                            Nullable] public string KiểuKháchHàng                                  { get; set; } // varchar(50)
		[Column("Hạng Khách hàng"),                                            Nullable] public string HạngKháchHàng                                  { get; set; } // varchar(50)
		[Column("Tên Khách hàng"),                                             Nullable] public string TênKháchHàng                                   { get; set; } // varchar(150)
		[Column("Mã khách hàng"),                                              Nullable] public string MãKháchHàng                                    { get; set; } // varchar(50)
		[Column("Số hợp đồng"),                                                Nullable] public string SốHợpĐồng                                      { get; set; } // varchar(250)
		[Column("Ngày ký HĐ"),                                                 Nullable] public string NgàyKýHĐ                                       { get; set; } // varchar(50)
		[Column("Ngày nghiệm thu tính cước"),                                  Nullable] public string NgàyNghiệmThuTínhCước                          { get; set; } // varchar(50)
		[Column("Năm ký hợp đồng"),                                            Nullable] public string NămKýHợpĐồng                                   { get; set; } // varchar(50)
		[Column("Năm NT tính cước"),                                           Nullable] public int?   NămNTTínhCước                                  { get; set; } // int
		[Column("Ngày ký HĐ (nâng cấp)"),                                      Nullable] public string NgàyKýHĐ_nângCấp_                              { get; set; } // varchar(50)
		[Column("Ngày nghiệm thu tính cước (nâng cấp)"),                       Nullable] public string NgàyNghiệmThuTínhCước_nângCấp_                 { get; set; } // varchar(50)
		[Column("Chi tiết triển khai CCDV"),                                   Nullable] public string ChiTiếtTriểnKhaiCCDV                           { get; set; } // varchar(100)
		[Column("Tình trạng CCDV"),                                            Nullable] public string TìnhTrạngCCDV                                  { get; set; } // varchar(100)
		[Column("Ngày thanh lý/giảm giá"),                                     Nullable] public string NgàyThanhLý_giảmGiá                            { get; set; } // varchar(50)
		[Column("Lý do thanh lý/giảm giá/tạm ngưng"),                          Nullable] public string LýDoThanhLý_giảmGiá_tạmNgưng                   { get; set; } // text
		[Column("Phân loại thanh lý/giảm giá/tạm ngưng"),                      Nullable] public string PhânLoạiThanhLý_giảmGiá_tạmNgưng               { get; set; } // varchar(50)
		[Column("Tình trạng HĐ"),                                              Nullable] public string TìnhTrạngHĐ                                    { get; set; } // varchar(50)
		[Column("Loại trừ KPI"),                                               Nullable] public string LoạiTrừKPI                                     { get; set; } // varchar(50)
		[Column("Thanh lý trước hạn"),                                         Nullable] public string ThanhLýTrướcHạn                                { get; set; } // varchar(50)
		[Column("Doanh thu mất đi do thanh lý (theo term HĐ)"),                Nullable] public string DoanhThuMấtĐiDoThanhLý_theoTermHĐ_             { get; set; } // varchar(50)
		[Column("Thời hạn HĐ"),                                                Nullable] public string ThờiHạnHĐ                                      { get; set; } // varchar(50)
		[Column("Loại HĐ (1 lần hay hàng tháng)"),                             Nullable] public string LoạiHĐ_1LầnHayHàngTháng_                       { get; set; } // varchar(100)
		[Column("CID / User"),                                                 Nullable] public string CID_User                                       { get; set; } // varchar(100)
		[Column("Điểm đầu"),                                                   Nullable] public string ĐiểmĐầu                                        { get; set; } // text
		[Column("Điểm cuối"),                                                  Nullable] public string ĐiểmCuối                                       { get; set; } // varchar(150)
		[Column("Chi tiết dịch vụ"),                                           Nullable] public string ChiTiếtDịchVụ                                  { get; set; } // varchar(200)
		[Column("Băng thông trong nước (M)"),                                  Nullable] public string BăngThôngTrongNước_M_                          { get; set; } // varchar(50)
		[Column("Băng thông quốc tế (M)"),                                     Nullable] public string BăngThôngQuốcTế_M_                             { get; set; } // varchar(50)
		[Column("Phạm vi kênh"),                                               Nullable] public string PhạmViKênh                                     { get; set; } // varchar(50)
		[Column("Loại doanh thu"),                                             Nullable] public string LoạiDoanhThu                                   { get; set; } // varchar(50)
		[Column("Loại dịch vụ"),                                               Nullable] public string LoạiDịchVụ                                     { get; set; } // varchar(150)
		[Column("Tranding (Yes/No)"),                                          Nullable] public string Tranding_Yes_No_                               { get; set; } // varchar(50)
		[Column("cước cài đặt (USD)"),                                         Nullable] public string CướcCàiĐặt_USD_                                { get; set; } // varchar(50)
		[Column("cước cài đặt (VNĐ)"),                                         Nullable] public string CướcCàiĐặt_VNĐ_                                { get; set; } // varchar(50)
		[Column("Cước hàng tháng (USD) 2021"),                                 Nullable] public string CướcHàngTháng_USD_2021                         { get; set; } // varchar(50)
		[Column("Cước hàng tháng (VNĐ) (trước VAT) 2021"),                     Nullable] public string CướcHàngTháng_VNĐ__trướcVAT_2021               { get; set; } // varchar(50)
		[Column("Cước hàng tháng (USD) 2022"),                                 Nullable] public string CướcHàngTháng_USD_2022                         { get; set; } // varchar(50)
		[Column("Cước hàng tháng (VNĐ) (trước VAT) 2022"),                     Nullable] public string CướcHàngTháng_VNĐ__trướcVAT_2022               { get; set; } // varchar(50)
		[Column("Cước hàng tháng (VNĐ) (Đã bao gồm VAT) 2022"),                Nullable] public string CướcHàngTháng_VNĐ__ĐãBaoGồmVAT_2022            { get; set; } // varchar(100)
		[Column("Chi phí đầu vào"),                                            Nullable] public string ChiPhíĐầuVào                                   { get; set; } // varchar(50)
		[Column("Số hợp đồng đầu vào liên quan"),                              Nullable] public string SốHợpĐồngĐầuVàoLiênQuan                        { get; set; } // varchar(100)
		[Column("Đối tác/Tỷ lệ phân chia DT"),                                 Nullable] public string ĐốiTác_TỷLệPhânChiaDT                          { get; set; } // varchar(250)
		[Column("Tỷ lệ phân chí doanh thu"),                                   Nullable] public string TỷLệPhânChíDoanhThu                            { get; set; } // varchar(50)
		[Column("Tỷ lệ hoa hồng"),                                             Nullable] public string TỷLệHoaHồng                                    { get; set; } // varchar(50)
		[Column("Ghi chú"),                                                    Nullable] public string GhiChú                                         { get; set; } // varchar(100)
		[Column("CS phụ trách"),                                               Nullable] public string CSPhụTrách                                     { get; set; } // varchar(50)
		[Column("KD phụ trách"),                                               Nullable] public string KDPhụTrách                                     { get; set; } // varchar(50)
		[Column("Bộ phận kí HĐ"),                                              Nullable] public string BộPhậnKíHĐ                                     { get; set; } // varchar(50)
		[Column("Ban QL KH"),                                                  Nullable] public string BanQLKH                                        { get; set; } // varchar(50)
		[Column("Nền 2020 chuyển sang 2021 chốt tại thời điểm 31/12/2020"),    Nullable] public string Nền2020ChuyểnSang2021ChốtTạiThờiĐiểm31_12_2020 { get; set; } // varchar(50)
		[Column("Giảm nền do thanh lý/giảm giá/tạm ngưng"),                    Nullable] public string GiảmNềnDoThanhLý_giảmGiá_tạmNgưng              { get; set; } // varchar(50)
		[Column("Phát triển mới năm 2021"),                                    Nullable] public string PhátTriểnMớiNăm2021                            { get; set; } // varchar(50)
		[Column("Giảm giá do dịch"),                                           Nullable] public string GiảmGiáDoDịch                                  { get; set; } // varchar(100)
		[Column("Năm 2021"),                                                   Nullable] public string Năm2021                                        { get; set; } // varchar(255)
		[Column("Tháng 1 - GT Hợp đồng"),                                      Nullable] public string Tháng1_GTHợpĐồng                               { get; set; } // varchar(50)
		[Column("Tháng 1 - GT Phát triển mới"),                                Nullable] public string Tháng1_GTPhátTriểnMới                          { get; set; } // varchar(50)
		[Column("Tháng 1 - GT Giảm nền"),                                      Nullable] public string Tháng1_GTGiảmNền                               { get; set; } // varchar(50)
		[Column("Tháng 2 - GT Hợp đồng"),                                      Nullable] public string Tháng2_GTHợpĐồng                               { get; set; } // varchar(50)
		[Column("Tháng 2 - GT Phát triển mới"),                                Nullable] public string Tháng2_GTPhátTriểnMới                          { get; set; } // varchar(50)
		[Column("Tháng 2 - GT Giảm nền"),                                      Nullable] public string Tháng2_GTGiảmNền                               { get; set; } // varchar(50)
		[Column("Tháng 3 - GT Hợp đồng"),                                      Nullable] public string Tháng3_GTHợpĐồng                               { get; set; } // varchar(50)
		[Column("Tháng 3 - GT Phát triển mới"),                                Nullable] public string Tháng3_GTPhátTriểnMới                          { get; set; } // varchar(50)
		[Column("Tháng 3 - GT Giảm nền"),                                      Nullable] public string Tháng3_GTGiảmNền                               { get; set; } // varchar(50)
		[Column("Tháng 4 - GT Hợp đồng"),                                      Nullable] public string Tháng4_GTHợpĐồng                               { get; set; } // varchar(50)
		[Column("Tháng 4 - GT Phát triển mới"),                                Nullable] public string Tháng4_GTPhátTriểnMới                          { get; set; } // varchar(50)
		[Column("Tháng 4 - GT Giảm nền"),                                      Nullable] public string Tháng4_GTGiảmNền                               { get; set; } // varchar(50)
		[Column("Tháng 5 - GT Hợp đồng"),                                      Nullable] public string Tháng5_GTHợpĐồng                               { get; set; } // varchar(50)
		[Column("Tháng 5 - GT Phát triển mới"),                                Nullable] public string Tháng5_GTPhátTriểnMới                          { get; set; } // varchar(50)
		[Column("Tháng 5 - GT Giảm nền"),                                      Nullable] public string Tháng5_GTGiảmNền                               { get; set; } // varchar(50)
		[Column("Tháng 6 - GT Hợp đồng"),                                      Nullable] public string Tháng6_GTHợpĐồng                               { get; set; } // varchar(50)
		[Column("Tháng 6 - GT Phát triển mới"),                                Nullable] public string Tháng6_GTPhátTriểnMới                          { get; set; } // varchar(50)
		[Column("Tháng 6 - GT Giảm nền"),                                      Nullable] public string Tháng6_GTGiảmNền                               { get; set; } // varchar(50)
		[Column("Tháng 7 - GT Hợp đồng"),                                      Nullable] public string Tháng7_GTHợpĐồng                               { get; set; } // varchar(50)
		[Column("Tháng 7 - GT Phát triển mới"),                                Nullable] public string Tháng7_GTPhátTriểnMới                          { get; set; } // varchar(50)
		[Column("Tháng 7 - GT Giảm nền"),                                      Nullable] public string Tháng7_GTGiảmNền                               { get; set; } // varchar(50)
		[Column("Tháng 8 - GT Hợp đồng"),                                      Nullable] public string Tháng8_GTHợpĐồng                               { get; set; } // varchar(255)
		[Column("Tháng 8 - GT Phát triển mới"),                                Nullable] public string Tháng8_GTPhátTriểnMới                          { get; set; } // varchar(50)
		[Column("Tháng 8 - GT Giảm nền"),                                      Nullable] public string Tháng8_GTGiảmNền                               { get; set; } // varchar(50)
		[Column("Tháng 9 - GT Hợp đồng"),                                      Nullable] public string Tháng9_GTHợpĐồng                               { get; set; } // varchar(255)
		[Column("Tháng 9 - GT Phát triển mới"),                                Nullable] public string Tháng9_GTPhátTriểnMới                          { get; set; } // varchar(50)
		[Column("Tháng 9 - GT Giảm nền"),                                      Nullable] public string Tháng9_GTGiảmNền                               { get; set; } // varchar(50)
		[Column("Tháng 10 - GT Hợp đồng"),                                     Nullable] public string Tháng10_GTHợpĐồng                              { get; set; } // varchar(255)
		[Column("Tháng 10 - GT Phát triển mới"),                               Nullable] public string Tháng10_GTPhátTriểnMới                         { get; set; } // varchar(50)
		[Column("Tháng 10 - GT Giảm nền"),                                     Nullable] public string Tháng10_GTGiảmNền                              { get; set; } // varchar(50)
		[Column("Tháng 11 - GT Hợp đồng"),                                     Nullable] public string Tháng11_GTHợpĐồng                              { get; set; } // varchar(255)
		[Column("Tháng 11 - GT Phát triển mới"),                               Nullable] public string Tháng11_GTPhátTriểnMới                         { get; set; } // varchar(50)
		[Column("Tháng 11 - GT Giảm nền"),                                     Nullable] public string Tháng11_GTGiảmNền                              { get; set; } // varchar(50)
		[Column("Tháng 12 - GT Hợp đồng"),                                     Nullable] public string Tháng12_GTHợpĐồng                              { get; set; } // varchar(255)
		[Column("Tháng 12 - GT Phát triển mới"),                               Nullable] public string Tháng12_GTPhátTriểnMới                         { get; set; } // varchar(50)
		[Column("Tháng 12 - GT Giảm nền"),                                     Nullable] public string Tháng12_GTGiảmNền                              { get; set; } // varchar(50)
		[Column("Tổng GTHĐ \n(term 12 tháng)\nUSD"),                           Nullable] public string TổngGTHĐ__term12Tháng__USD                     { get; set; } // varchar(255)
		[Column("Tổng GTHĐ \n(term 12 tháng)\nVND"),                           Nullable] public string TổngGTHĐ__term12Tháng__VND                     { get; set; } // varchar(255)
		[Column("Tổng cài đặt (USD)"),                                         Nullable] public string TổngCàiĐặt_USD_                                { get; set; } // varchar(255)
		[Column("Tổng cài đặt VND"),                                           Nullable] public string TổngCàiĐặtVND                                  { get; set; } // varchar(255)
		[Column("Tổng PTM đã ký trong năm 2022"),                              Nullable] public string TổngPTMĐãKýTrongNăm2022                        { get; set; } // varchar(255)
		[Column("Tổng  PTM đã NT trong năm 2022"),                             Nullable] public string TổngPTMĐãNTTrongNăm2022                        { get; set; } // varchar(255)
		[Column("Tổng cộng HĐ đã ký"),                                         Nullable] public string TổngCộngHĐĐãKý                                 { get; set; } // varchar(255)
		[Column("Tổng HĐ đã NT"),                                              Nullable] public string TổngHĐĐãNT                                     { get; set; } // varchar(255)
		[Column("Ktra công thức"),                                             Nullable] public string KtraCôngThức                                   { get; set; } // varchar(50)
		[Column("Tháng tính KPI"),                                             Nullable] public string ThángTínhKPI                                   { get; set; } // varchar(50)
		[Column("Ghi chú cho KPI"),                                            Nullable] public string GhiChúChoKPI                                   { get; set; } // varchar(50)
		[Column("Thanh lý năm"),                                               Nullable] public string ThanhLýNăm                                     { get; set; } // varchar(50)
	}

	[Serializable]
	[Table("MasterVTCNTT")]
	public partial class MasterVTCNTT : BaseEntity
	{
		[Column("Tuần báo cáo"),                                               Nullable] public string  TuầnBáoCáo                                     { get; set; } // varchar(50)
		[Column("KH nền -0 hay mới - 1"),                                      Nullable] public int?    KHNền_0HayMới_1                                { get; set; } // int
		[Column("Qua đại lý/ KH cuối"),                                        Nullable] public string  QuaĐạiLý_KHCuối                                { get; set; } // varchar(50)
		[Column("Khu vực"),                                                    Nullable] public string  KhuVực                                         { get; set; } // varchar(50)
		[Column("Danh mục khách hàng"),                                        Nullable] public string  DanhMụcKháchHàng                               { get; set; } // varchar(50)
		[Column("Nhóm khách hàng"),                                            Nullable] public string  NhómKháchHàng                                  { get; set; } // varchar(50)
		[Column("Loại hình cơ cấu Kh"),                                        Nullable] public string  LoạiHìnhCơCấuKh                                { get; set; } // varchar(50)
		[Column("Kiểu Khách hàng"),                                            Nullable] public string  KiểuKháchHàng                                  { get; set; } // varchar(50)
		[Column("Hạng Khách hàng"),                                            Nullable] public string  HạngKháchHàng                                  { get; set; } // varchar(50)
		[Column("Tên Khách hàng"),                                             Nullable] public string  TênKháchHàng                                   { get; set; } // varchar(50)
		[Column("Mã khách hàng"),                                              Nullable] public string  MãKháchHàng                                    { get; set; } // varchar(50)
		[Column("Số hợp đồng"),                                                Nullable] public string  SốHợpĐồng                                      { get; set; } // varchar(100)
		[Column("Ngày ký HĐ"),                                                 Nullable] public string  NgàyKýHĐ                                       { get; set; } // varchar(50)
		[Column("Ngày nghiệm thu tính cước"),                                  Nullable] public string  NgàyNghiệmThuTínhCước                          { get; set; } // varchar(50)
		[Column("Năm ký hợp đồng"),                                            Nullable] public int?    NămKýHợpĐồng                                   { get; set; } // int
		[Column("Năm NT tính cước"),                                           Nullable] public int?    NămNTTínhCước                                  { get; set; } // int
		[Column("Ngày ký HĐ (nâng cấp)"),                                      Nullable] public string  NgàyKýHĐ_nângCấp_                              { get; set; } // varchar(50)
		[Column("Ngày nghiệm thu tính cước (nâng cấp)"),                       Nullable] public string  NgàyNghiệmThuTínhCước_nângCấp_                 { get; set; } // varchar(50)
		[Column("Chi tiết triển khai CCDV"),                                   Nullable] public string  ChiTiếtTriểnKhaiCCDV                           { get; set; } // varchar(50)
		[Column("Tình trạng CCDV"),                                            Nullable] public string  TìnhTrạngCCDV                                  { get; set; } // varchar(50)
		[Column("Ngày thanh lý/giảm giá"),                                     Nullable] public string  NgàyThanhLý_giảmGiá                            { get; set; } // varchar(50)
		[Column("Lý do thanh lý/giảm giá/tạm ngưng"),                          Nullable] public string  LýDoThanhLý_giảmGiá_tạmNgưng                   { get; set; } // varchar(100)
		[Column("Phân loại thanh lý/giảm giá/tạm ngưng"),                      Nullable] public string  PhânLoạiThanhLý_giảmGiá_tạmNgưng               { get; set; } // varchar(50)
		[Column("Tình trạng HĐ"),                                              Nullable] public string  TìnhTrạngHĐ                                    { get; set; } // varchar(50)
		[Column("Loại trừ KPI"),                                               Nullable] public string  LoạiTrừKPI                                     { get; set; } // varchar(50)
		[Column("Thanh lý trước hạn"),                                         Nullable] public string  ThanhLýTrướcHạn                                { get; set; } // varchar(50)
		[Column("Doanh thu mất đi do thanh lý (theo term HĐ)"),                Nullable] public string  DoanhThuMấtĐiDoThanhLý_theoTermHĐ_             { get; set; } // varchar(50)
		[Column("Thời hạn HĐ"),                                                Nullable] public string  ThờiHạnHĐ                                      { get; set; } // varchar(50)
		[Column("Loại HĐ (1 lần hay hàng tháng)"),                             Nullable] public string  LoạiHĐ_1LầnHayHàngTháng_                       { get; set; } // varchar(50)
		[Column("CID / User"),                                                 Nullable] public string  CID_User                                       { get; set; } // varchar(50)
		[Column("Điểm đầu"),                                                   Nullable] public string  ĐiểmĐầu                                        { get; set; } // varchar(150)
		[Column("Điểm cuối"),                                                  Nullable] public string  ĐiểmCuối                                       { get; set; } // varchar(100)
		[Column("Chi tiết dịch vụ"),                                           Nullable] public string  ChiTiếtDịchVụ                                  { get; set; } // varchar(50)
		[Column("Băng thông trong nước (M)"),                                  Nullable] public string  BăngThôngTrongNước_M_                          { get; set; } // varchar(50)
		[Column("Băng thông quốc tế (M)"),                                     Nullable] public string  BăngThôngQuốcTế_M_                             { get; set; } // varchar(50)
		[Column("Phạm vi kênh"),                                               Nullable] public string  PhạmViKênh                                     { get; set; } // varchar(50)
		[Column("Loại doanh thu"),                                             Nullable] public string  LoạiDoanhThu                                   { get; set; } // varchar(50)
		[Column("Loại dịch vụ"),                                               Nullable] public string  LoạiDịchVụ                                     { get; set; } // varchar(100)
		[Column("Tranding (Yes/No)"),                                          Nullable] public string  Tranding_Yes_No_                               { get; set; } // varchar(50)
		[Column("cước cài đặt (USD)"),                                         Nullable] public string  CướcCàiĐặt_USD_                                { get; set; } // varchar(50)
		[Column("cước cài đặt (VNĐ)"),                                         Nullable] public string  CướcCàiĐặt_VNĐ_                                { get; set; } // varchar(50)
		[Column("Cước hàng tháng (USD) 2020"),                                 Nullable] public string  CướcHàngTháng_USD_2020                         { get; set; } // varchar(50)
		[Column("Cước hàng tháng (VNĐ) (trước VAT) 2020"),                     Nullable] public string  CướcHàngTháng_VNĐ__trướcVAT_2020               { get; set; } // varchar(50)
		[Column("Cước hàng tháng (USD) 2021"),                                 Nullable] public string  CướcHàngTháng_USD_2021                         { get; set; } // varchar(50)
		[Column("Cước hàng tháng (VNĐ) (trước VAT) 2021"),                     Nullable] public string  CướcHàngTháng_VNĐ__trướcVAT_2021               { get; set; } // varchar(50)
		[Column("Cước hàng tháng (VNĐ) (Đã bao gồm VAT) 2021"),                Nullable] public string  CướcHàngTháng_VNĐ__ĐãBaoGồmVAT_2021            { get; set; } // varchar(50)
		[Column("Chi phí đầu vào (cước tháng)"),                               Nullable] public string  ChiPhíĐầuVào_cướcTháng_                        { get; set; } // varchar(50)
		[Column("Số hợp đồng đầu vào liên quan"),                              Nullable] public string  SốHợpĐồngĐầuVàoLiênQuan                        { get; set; } // varchar(50)
		[Column("Đối tác/Tỷ lệ phân chia DT"),                                 Nullable] public string  ĐốiTác_TỷLệPhânChiaDT                          { get; set; } // varchar(50)
		[Column("Tỷ lệ phân chí doanh thu"),                                   Nullable] public string  TỷLệPhânChíDoanhThu                            { get; set; } // varchar(50)
		[Column("Tỷ lệ hoa hồng"),                                             Nullable] public string  TỷLệHoaHồng                                    { get; set; } // varchar(50)
		[Column("Ghi chú"),                                                    Nullable] public string  GhiChú                                         { get; set; } // varchar(50)
		[Column("CS phụ trách"),                                               Nullable] public string  CSPhụTrách                                     { get; set; } // varchar(50)
		[Column("KD phụ trách"),                                               Nullable] public string  KDPhụTrách                                     { get; set; } // varchar(50)
		[Column("Bộ phận kí HĐ"),                                              Nullable] public string  BộPhậnKíHĐ                                     { get; set; } // varchar(50)
		[Column("Ban QL KH"),                                                  Nullable] public string  BanQLKH                                        { get; set; } // varchar(50)
		[Column("Nền 2020 chuyển sang 2021 chốt tại thời điểm 31/12/2020"),    Nullable] public string  Nền2020ChuyểnSang2021ChốtTạiThờiĐiểm31_12_2020 { get; set; } // varchar(50)
		[Column("Giảm nền do thanh lý/giảm giá/tạm ngưng"),                    Nullable] public string  GiảmNềnDoThanhLý_giảmGiá_tạmNgưng              { get; set; } // varchar(50)
		[Column("Phát triển mới năm 2021"),                                    Nullable] public string  PhátTriểnMớiNăm2021                            { get; set; } // varchar(50)
		[Column("Giảm giá do dịch"),                                           Nullable] public string  GiảmGiáDoDịch                                  { get; set; } // varchar(50)
		[Column("Năm 2021"),                                                   Nullable] public string  Năm2021                                        { get; set; } // varchar(50)
		[Column("Tháng 1 - GT Hợp đồng"),                                      Nullable] public string  Tháng1_GTHợpĐồng                               { get; set; } // varchar(50)
		[Column("Tháng 1 - GT Phát triển mới"),                                Nullable] public string  Tháng1_GTPhátTriểnMới                          { get; set; } // varchar(50)
		[Column("Tháng 1 - GT Giảm nền"),                                      Nullable] public string  Tháng1_GTGiảmNền                               { get; set; } // varchar(50)
		[Column("Tháng 2 - GT Hợp đồng"),                                      Nullable] public string  Tháng2_GTHợpĐồng                               { get; set; } // varchar(50)
		[Column("Tháng 2 - GT Phát triển mới"),                                Nullable] public string  Tháng2_GTPhátTriểnMới                          { get; set; } // varchar(50)
		[Column("Tháng 2 - GT Giảm nền"),                                      Nullable] public string  Tháng2_GTGiảmNền                               { get; set; } // varchar(50)
		[Column("Tháng 3 - GT Hợp đồng"),                                      Nullable] public string  Tháng3_GTHợpĐồng                               { get; set; } // varchar(50)
		[Column("Tháng 3 - GT Phát triển mới"),                                Nullable] public string  Tháng3_GTPhátTriểnMới                          { get; set; } // varchar(50)
		[Column("Tháng 3 - GT Giảm nền"),                                      Nullable] public string  Tháng3_GTGiảmNền                               { get; set; } // varchar(50)
		[Column("Tháng 4 - GT Hợp đồng"),                                      Nullable] public string  Tháng4_GTHợpĐồng                               { get; set; } // varchar(50)
		[Column("Tháng 4 - GT Phát triển mới"),                                Nullable] public string  Tháng4_GTPhátTriểnMới                          { get; set; } // varchar(50)
		[Column("Tháng 4 - GT Giảm nền"),                                      Nullable] public string  Tháng4_GTGiảmNền                               { get; set; } // varchar(50)
		[Column("Tháng 5 - GT Hợp đồng"),                                      Nullable] public string  Tháng5_GTHợpĐồng                               { get; set; } // varchar(50)
		[Column("Tháng 5 - GT Phát triển mới"),                                Nullable] public string  Tháng5_GTPhátTriểnMới                          { get; set; } // varchar(50)
		[Column("Tháng 5 - GT Giảm nền"),                                      Nullable] public string  Tháng5_GTGiảmNền                               { get; set; } // varchar(50)
		[Column("Tháng 6 - GT Hợp đồng"),                                      Nullable] public string  Tháng6_GTHợpĐồng                               { get; set; } // varchar(50)
		[Column("Tháng 6 - GT Phát triển mới"),                                Nullable] public string  Tháng6_GTPhátTriểnMới                          { get; set; } // varchar(50)
		[Column("Tháng 6 - GT Giảm nền"),                                      Nullable] public string  Tháng6_GTGiảmNền                               { get; set; } // varchar(50)
		[Column("Tháng 7 - GT Hợp đồng"),                                      Nullable] public string  Tháng7_GTHợpĐồng                               { get; set; } // varchar(50)
		[Column("Tháng 7 - GT Phát triển mới"),                                Nullable] public string  Tháng7_GTPhátTriểnMới                          { get; set; } // varchar(50)
		[Column("Tháng 7 - GT Giảm nền"),                                      Nullable] public string  Tháng7_GTGiảmNền                               { get; set; } // varchar(50)
		[Column("Tháng 8 - GT Hợp đồng"),                                      Nullable] public string  Tháng8_GTHợpĐồng                               { get; set; } // varchar(50)
		[Column("Tháng 8 - GT Phát triển mới"),                                Nullable] public string  Tháng8_GTPhátTriểnMới                          { get; set; } // varchar(50)
		[Column("Tháng 8 - GT Giảm nền"),                                      Nullable] public string  Tháng8_GTGiảmNền                               { get; set; } // varchar(50)
		[Column("Tháng 9 - GT Hợp đồng"),                                      Nullable] public string  Tháng9_GTHợpĐồng                               { get; set; } // varchar(50)
		[Column("Tháng 9 - GT Phát triển mới"),                                Nullable] public string  Tháng9_GTPhátTriểnMới                          { get; set; } // varchar(50)
		[Column("Tháng 9 - GT Giảm nền"),                                      Nullable] public string  Tháng9_GTGiảmNền                               { get; set; } // varchar(50)
		[Column("Tháng 10 - GT Hợp đồng"),                                     Nullable] public string  Tháng10_GTHợpĐồng                              { get; set; } // varchar(50)
		[Column("Tháng 10 - GT Phát triển mới"),                               Nullable] public string  Tháng10_GTPhátTriểnMới                         { get; set; } // varchar(50)
		[Column("Tháng 10 - GT Giảm nền"),                                     Nullable] public string  Tháng10_GTGiảmNền                              { get; set; } // varchar(50)
		[Column("Tháng 11 - GT Hợp đồng"),                                     Nullable] public string  Tháng11_GTHợpĐồng                              { get; set; } // varchar(50)
		[Column("Tháng 11 - GT Phát triển mới"),                               Nullable] public string  Tháng11_GTPhátTriểnMới                         { get; set; } // varchar(50)
		[Column("Tháng 11 - GT Giảm nền"),                                     Nullable] public string  Tháng11_GTGiảmNền                              { get; set; } // varchar(50)
		[Column("Tháng 12 - GT Hợp đồng"),                                     Nullable] public string  Tháng12_GTHợpĐồng                              { get; set; } // varchar(50)
		[Column("Tháng 12 - GT Phát triển mới"),                               Nullable] public string  Tháng12_GTPhátTriểnMới                         { get; set; } // varchar(50)
		[Column("Tháng 12 - GT Giảm nền"),                                     Nullable] public string  Tháng12_GTGiảmNền                              { get; set; } // varchar(50)
		[Column("Tổng GTHĐ \n(term 12 tháng)\nUSD"),                           Nullable] public int?    TổngGTHĐ__term12Tháng__USD                     { get; set; } // int
		[Column("Tổng GTHĐ \n(term 12 tháng)\nVND"),                           Nullable] public double? TổngGTHĐ__term12Tháng__VND                     { get; set; } // double(10,3)
		[Column("Tổng cài đặt (USD)"),                                         Nullable] public int?    TổngCàiĐặt_USD_                                { get; set; } // int
		[Column("Tổng cài đặt VND"),                                           Nullable] public string  TổngCàiĐặtVND                                  { get; set; } // varchar(50)
		[Column("Tổng PTM đã ký trong năm 2021"),                              Nullable] public string  TổngPTMĐãKýTrongNăm2021                        { get; set; } // varchar(50)
		[Column("Tổng  PTM đã NT trong năm 2021"),                             Nullable] public string  TổngPTMĐãNTTrongNăm2021                        { get; set; } // varchar(50)
		[Column("Tổng cộng HĐ đã ký"),                                         Nullable] public string  TổngCộngHĐĐãKý                                 { get; set; } // varchar(50)
		[Column("Tổng HĐ đã NT"),                                              Nullable] public string  TổngHĐĐãNT                                     { get; set; } // varchar(50)
		[Column("Ktra công thức"),                                             Nullable] public string  KtraCôngThức                                   { get; set; } // varchar(50)
		[Column("Tháng tính KPI"),                                             Nullable] public string  ThángTínhKPI                                   { get; set; } // varchar(50)
		[Column("Ghi chú cho KPI"),                                            Nullable] public string  GhiChúChoKPI                                   { get; set; } // varchar(50)
		[Column("Thanh lý năm"),                                               Nullable] public string  ThanhLýNăm                                     { get; set; } // varchar(50)
	}

	[Serializable]
	[Table("NameTableExist")]
	public partial class NameTableExist : BaseEntity
	{
		[Column, NotNull    ] public string Name    { get; set; } // varchar(50)
		[Column,    Nullable] public string NameDes { get; set; } // varchar(255)
	}

	[Serializable]
	[Table("Report")]
	public partial class Report : BaseEntity
	{
		[Column, NotNull    ] public string ReportGroupId { get; set; } // varchar(36)
		[Column, NotNull    ] public string Name          { get; set; } // varchar(255)
		[Column,    Nullable] public string Description   { get; set; } // varchar(4000)
		[Column,    Nullable] public byte[] ExcelData     { get; set; } // longblob
		[Column,    Nullable] public string TableRefs     { get; set; } // varchar(1000)
		/// <summary>
		/// Ngừng theo dõi
		/// </summary>
		[Column, NotNull    ] public bool   Inactive      { get; set; } // bit(1)

		#region Associations

		/// <summary>
		/// FK_Reports_PK_ReportGroup
		/// </summary>
		[Association(ThisKey="ReportGroupId", OtherKey="Id", CanBeNull=false, Relationship=LinqToDB.Mapping.Relationship.ManyToOne, KeyName="FK_Reports_PK_ReportGroup", BackReferenceName="Reports")]
		public ReportGroup ReportGroup { get; set; }

		#endregion
	}

	[Serializable]
	[Table("ReportGroup")]
	public partial class ReportGroup : BaseEntity
	{
		[Column,    Nullable] public string ParentId    { get; set; } // varchar(36)
		[Column, NotNull    ] public string Name        { get; set; } // varchar(255)
		[Column,    Nullable] public string Description { get; set; } // varchar(4000)
		[Column,    Nullable] public string Path        { get; set; } // varchar(1000)
		/// <summary>
		/// Ngừng theo dõi
		/// </summary>
		[Column, NotNull    ] public bool   Inactive    { get; set; } // bit(1)

		#region Associations

		/// <summary>
		/// FK_ReportGroups_PK_Parent
		/// </summary>
		[Association(ThisKey="ParentId", OtherKey="Id", CanBeNull=true, Relationship=LinqToDB.Mapping.Relationship.ManyToOne, KeyName="FK_ReportGroups_PK_Parent", BackReferenceName="ReportGroups")]
		public ReportGroup Parent { get; set; }

		/// <summary>
		/// FK_ReportGroups_PK_Parent_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="ParentId", CanBeNull=true, Relationship=LinqToDB.Mapping.Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ReportGroup> ReportGroups { get; set; }

		/// <summary>
		/// FK_Reports_PK_ReportGroup_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="ReportGroupId", CanBeNull=true, Relationship=LinqToDB.Mapping.Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Report> Reports { get; set; }

		#endregion
	}

	[Serializable]
	[Table("RosePrice")]
	public partial class RosePrice : BaseEntity
	{
		[Column(),                                     Nullable] public string   Loại                        { get; set; } // varchar(50)
		[Column(),                                     Nullable] public string   Miền                        { get; set; } // varchar(50)
		[Column("Đối tượng ký HĐ"),                    Nullable] public string   ĐốiTượngKýHĐ                { get; set; } // varchar(50)
		[Column("Tình trạng HĐ"),                      Nullable] public string   TìnhTrạngHĐ                 { get; set; } // varchar(50)
		[Column("Tên Đối tác"),                        Nullable] public string   TênĐốiTác                   { get; set; } // varchar(100)
		[Column("Số hợp đồng"),                        Nullable] public string   SốHợpĐồng                   { get; set; } // varchar(100)
		[Column("Khách hàng đầu ra"),                  Nullable] public string   KháchHàngĐầuRa              { get; set; } // varchar(150)
		[Column("HĐ đầu ra"),                          Nullable] public string   HĐĐầuRa                     { get; set; } // varchar(150)
		[Column("Loại chi phí"),                       Nullable] public string   LoạiChiPhí                  { get; set; } // varchar(50)
		[Column("BP phụ trách"),                       Nullable] public string   BPPhụTrách                  { get; set; } // varchar(50)
		[Column("Đối tượng KH đầu ra"),                Nullable] public string   ĐốiTượngKHĐầuRa             { get; set; } // varchar(50)
		[Column("Ngày Thanh lý/ nghiệm thu"),          Nullable] public string   NgàyThanhLý_NghiệmThu       { get; set; } // varchar(50)
		[Column("Tỷ lệ"),                              Nullable] public string   TỷLệ                        { get; set; } // varchar(50)
		[Column("Nhóm HH/PCDT"),                       Nullable] public string   NhómHH_PCDT                 { get; set; } // varchar(50)
		[Column("Giá trị doanh thu đầu ra tháng VNĐ"), Nullable] public string   GiáTrịDoanhThuĐầuRaThángVNĐ { get; set; } // varchar(50)
		[Column("Tháng 1"),                            Nullable] public decimal? Tháng1                      { get; set; } // decimal(15,4)
		[Column("Tháng 2"),                            Nullable] public decimal? Tháng2                      { get; set; } // decimal(15,4)
		[Column("Tháng 3"),                            Nullable] public decimal? Tháng3                      { get; set; } // decimal(15,4)
		[Column("Tháng 4"),                            Nullable] public decimal? Tháng4                      { get; set; } // decimal(15,4)
		[Column("Tháng 5"),                            Nullable] public decimal? Tháng5                      { get; set; } // decimal(15,4)
		[Column("Tháng 6"),                            Nullable] public decimal? Tháng6                      { get; set; } // decimal(15,4)
		[Column("Tháng 7"),                            Nullable] public decimal? Tháng7                      { get; set; } // decimal(15,4)
		[Column("Tháng 8"),                            Nullable] public decimal? Tháng8                      { get; set; } // decimal(15,4)
		[Column("Tháng 9"),                            Nullable] public decimal? Tháng9                      { get; set; } // decimal(15,4)
		[Column("Tháng 10"),                           Nullable] public decimal? Tháng10                     { get; set; } // decimal(15,4)
		[Column("Tháng 11"),                           Nullable] public decimal? Tháng11                     { get; set; } // decimal(15,4)
		[Column("Tháng 12"),                           Nullable] public decimal? Tháng12                     { get; set; } // decimal(15,4)
		[Column("Năm 2021"),                           Nullable] public decimal? Năm2021                     { get; set; } // decimal(15,4)
	}

	[Serializable]
	[Table("SelectTable")]
	public partial class SelectTable : BaseEntity
	{
		[Column, NotNull] public string TextShow  { get; set; } // varchar(255)
		[Column, NotNull] public string ValueShow { get; set; } // varchar(255)
		[Column, NotNull] public string TableShow { get; set; } // varchar(255)
	}

	/// <summary>
	/// Danh mục Dữ liệu
	/// </summary>
	[Serializable]
	[Table("StorageValue")]
	public partial class StorageValue : BaseEntity
	{
		/// <summary>
		/// Tên dữ liệu
		/// </summary>
		[Column, NotNull    ] public string   Name               { get; set; } // varchar(100)
		/// <summary>
		/// Ngày
		/// </summary>
		[Column,    Nullable] public int?     TimeDay            { get; set; } // int
		/// <summary>
		/// Tháng
		/// </summary>
		[Column,    Nullable] public int?     TimeMouth          { get; set; } // int
		/// <summary>
		/// Năm
		/// </summary>
		[Column,    Nullable] public int?     TimeYear           { get; set; } // int
		/// <summary>
		/// Trạng thái
		/// </summary>
		[Column,    Nullable] public int?     Status             { get; set; } // int
		/// <summary>
		/// Ngày tạo
		/// </summary>
		[Column, NotNull    ] public DateTime CreatedDate        { get; set; } // datetime
		/// <summary>
		/// Người tạo
		/// </summary>
		[Column,    Nullable] public string   CreatedBy          { get; set; } // varchar(100)
		/// <summary>
		/// Ngày sửa gần nhất
		/// </summary>
		[Column, NotNull    ] public DateTime ModifiedDate       { get; set; } // timestamp
		/// <summary>
		/// Người sử gần nhất
		/// </summary>
		[Column,    Nullable] public string   ModifiedBy         { get; set; } // varchar(100)
		[Column, NotNull    ] public string   TypeValueId        { get; set; } // varchar(36)
		[Column,    Nullable] public string   SaveValue          { get; set; } // longtext
		[Column, NotNull    ] public DateTime VoucherDate        { get; set; } // timestamp
		[Column, NotNull    ] public string   VoucherBy          { get; set; } // varchar(255)
		[Column,    Nullable] public byte[]   DataSave           { get; set; } // longblob
		[Column,    Nullable] public string   FileName           { get; set; } // varchar(255)
		/// <summary>
		/// Kích thước File
		/// </summary>
		[Column,    Nullable] public decimal? FileLength         { get; set; } // decimal(10,0)
		/// <summary>
		/// Định dạng File
		/// </summary>
		[Column,    Nullable] public string   FileContent        { get; set; } // varchar(100)
		/// <summary>
		/// Đuôi file
		/// </summary>
		[Column,    Nullable] public string   FileType           { get; set; } // varchar(50)
		[Column,    Nullable] public string   VoucherByName      { get; set; } // varchar(255)
		[Column,    Nullable] public string   ModifiedByName     { get; set; } // varchar(255)
		[Column, NotNull    ] public int      NumberHeader       { get; set; } // int
		[Column,    Nullable] public string   NameTableRefense   { get; set; } // varchar(255)
		[Column,    Nullable] public string   SheeActive         { get; set; } // varchar(255)
		[Column,    Nullable] public string   UrlTemplate        { get; set; } // varchar(255)
		[Column, NotNull    ] public string   NameColumn         { get; set; } // varchar(255)
		[Column, NotNull    ] public int      TableHeaderRow     { get; set; } // int
		[Column,    Nullable] public string   TableSheetNames    { get; set; } // varchar(1000)
		[Column,    Nullable] public bool?    ActiveGetAllData   { get; set; } // bit(1)
		[Column,    Nullable] public string   OptionSelectColumn { get; set; } // varchar(255)

		#region Associations

		/// <summary>
		/// FK_TypeValueId_StorageValue_PK_TypeValueId
		/// </summary>
		[Association(ThisKey="TypeValueId", OtherKey="Id", CanBeNull=false, Relationship=LinqToDB.Mapping.Relationship.ManyToOne, KeyName="FK_TypeValueId_StorageValue_PK_TypeValueId", BackReferenceName="TypeValueId_StorageValues")]
		public TypeValue FKTypeValueId { get; set; }

		#endregion
	}

	/// <summary>
	/// Danh mục loại dữ liệu
	/// </summary>
	[Serializable]
	[Table("TypeValue")]
	public partial class TypeValue : BaseEntity
	{
		/// <summary>
		/// Tên loại dữ liệu
		/// </summary>
		[Column, NotNull    ] public string Name        { get; set; } // varchar(100)
		/// <summary>
		/// Mô tả
		/// </summary>
		[Column,    Nullable] public string Description { get; set; } // varchar(255)
		/// <summary>
		/// fk Id của kiểu cha
		/// </summary>
		[Column,    Nullable] public string ParentId    { get; set; } // varchar(36)
		/// <summary>
		/// HearachyID dạng path để hỗ trợ query dữ liệu dạng tree
		/// </summary>
		[Column,    Nullable] public string Path        { get; set; } // varchar(255)
		/// <summary>
		/// Ngừng theo dõi
		/// </summary>
		[Column, NotNull    ] public bool   Inactive    { get; set; } // bit(1)

		#region Associations

		/// <summary>
		/// FK_TypeValueId_StorageValue_PK_TypeValueId_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="TypeValueId", CanBeNull=true, Relationship=LinqToDB.Mapping.Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<StorageValue> TypeValueId_StorageValues { get; set; }

		#endregion
	}

	/// <summary>
	/// VIEW
	/// </summary>
	[Serializable]
	[Table("view2", IsView=true)]
	public partial class view2 : BaseEntity
	{
		[Column("Tuần cập nhật"),                                           Nullable] public string TuầnCậpNhật                               { get; set; } // varchar(50)
		[Column(),                                                          Nullable] public string Miền                                      { get; set; } // varchar(50)
		[Column("Tỉnh thành"),                                              Nullable] public string TỉnhThành                                 { get; set; } // varchar(50)
		[Column(),                                                          Nullable] public string Key                                       { get; set; } // varchar(151)
		[Column("Tình trạng hoạt động"),                                    Nullable] public string TìnhTrạngHoạtĐộng                         { get; set; } // varchar(50)
		[Column("Loại khách hàng"),                                         Nullable] public string LoạiKháchHàng                             { get; set; } // varchar(50)
		[Column("Khách hàng"),                                              Nullable] public string KháchHàng                                 { get; set; } // varchar(100)
		[Column("Số điện thoại"),                                           Nullable] public string SốĐiệnThoại                               { get; set; } // varchar(150)
		[Column("Địa chỉ"),                                                 Nullable] public string ĐịaChỉ                                    { get; set; } // varchar(150)
		[Column("Mã KH/CID"),                                               Nullable] public string MãKH_CID                                  { get; set; } // varchar(50)
		[Column("Số Hợp đồng"),                                             Nullable] public string SốHợpĐồng                                 { get; set; } // varchar(100)
		[Column("CS Phụ trách"),                                            Nullable] public string CSPhụTrách                                { get; set; } // varchar(50)
		[Column("Gói cước"),                                                Nullable] public string GóiCước                                   { get; set; } // varchar(50)
		[Column("Trả trước"),                                               Nullable] public string TrảTrước                                  { get; set; } // varchar(50)
		[Column("Số tháng được tặng trong 1 năm"),                          Nullable] public string SốThángĐượcTặngTrong1Năm                  { get; set; } // varchar(50)
		[Column("Số tháng dùng"),                                           Nullable] public string SốThángDùng                               { get; set; } // varchar(50)
		[Column("Cước hợp đồng hàng tháng"),                                Nullable] public string CướcHợpĐồngHàngTháng                      { get; set; } // varchar(50)
		[Column("Cước tháng Internet"),                                     Nullable] public string CướcThángInternet                         { get; set; } // varchar(50)
		[Column("Cước tháng truyền hình"),                                  Nullable] public string CướcThángTruyềnHình                       { get; set; } // varchar(50)
		[Column("Tỷ lệ chia sẻ cho đối tác phần Internet"),                 Nullable] public string TỷLệChiaSẻChoĐốiTácPhầnInternet           { get; set; } // varchar(255)
		[Column("Tỷ lệ chia sẻ cho đối tác phần truyền hình"),              Nullable] public string TỷLệChiaSẻChoĐốiTácPhầnTruyềnHình         { get; set; } // varchar(50)
		[Column("Cước HTC được nhận hàng tháng"),                           Nullable] public string CướcHTCĐượcNhậnHàngTháng                  { get; set; } // varchar(50)
		[Column("Cước HTC được nhận được TB sau khi trừ đi khuyến mại"),    Nullable] public string CướcHTCĐượcNhậnĐượcTBSauKhiTrừĐiKhuyếnMại { get; set; } // varchar(255)
		[Column("Cước đã thu lần 1"),                                       Nullable] public string CướcĐãThuLần1                             { get; set; } // varchar(50)
		[Column("Chủ thể xuất hóa đơn"),                                    Nullable] public string ChủThểXuấtHóaĐơn                          { get; set; } // varchar(50)
		[Column("Ngày ký HĐ/ lắp đặt"),                                     Nullable] public string NgàyKýHĐ_LắpĐặt                           { get; set; } // varchar(50)
		[Column("Ngày nghiệm thu"),                                         Nullable] public string NgàyNghiệmThu                             { get; set; } // varchar(50)
		[Column("Ngày hết hạn theo term 12 tháng"),                         Nullable] public string NgàyHếtHạnTheoTerm12Tháng                 { get; set; } // varchar(50)
		[Column("Ngày thanh lý"),                                           Nullable] public string NgàyThanhLý                               { get; set; } // varchar(50)
		[Column("Thanh lý (trước hạn hay sau hạn)"),                        Nullable] public string ThanhLý_trướcHạnHaySauHạn_                { get; set; } // varchar(50)
		[Column("Doanh thu mất đi do thanh lý (theo term HĐ)"),             Nullable] public string DoanhThuMấtĐiDoThanhLý_theoTermHĐ_        { get; set; } // varchar(50)
		[Column("Chi tiết lý do thanh lý"),                                 Nullable] public string ChiTiếtLýDoThanhLý                        { get; set; } // varchar(50)
		[Column("Phân loại thanh lý"),                                      Nullable] public string PhânLoạiThanhLý                           { get; set; } // varchar(50)
		[Column(),                                                          Nullable] public string Nền                                       { get; set; } // varchar(50)
		[Column("Giảm nền"),                                                Nullable] public string GiảmNền                                   { get; set; } // varchar(50)
		[Column("Doanh thu phát triển mới"),                                Nullable] public string DoanhThuPhátTriểnMới                      { get; set; } // varchar(255)
		[Column("Tổng DT"),                                                 Nullable] public string TổngDT                                    { get; set; } // varchar(50)
		[Column("Tháng 1"),                                                 Nullable] public string Tháng1                                    { get; set; } // varchar(50)
		[Column("Tháng 2"),                                                 Nullable] public string Tháng2                                    { get; set; } // varchar(50)
		[Column("Tháng 3"),                                                 Nullable] public string Tháng3                                    { get; set; } // varchar(50)
		[Column("Tháng 4"),                                                 Nullable] public string Tháng4                                    { get; set; } // varchar(50)
		[Column("Tháng 5"),                                                 Nullable] public string Tháng5                                    { get; set; } // varchar(50)
		[Column("Tháng 6"),                                                 Nullable] public string Tháng6                                    { get; set; } // varchar(50)
		[Column("Tháng 7"),                                                 Nullable] public string Tháng7                                    { get; set; } // varchar(50)
		[Column("Tháng 8"),                                                 Nullable] public string Tháng8                                    { get; set; } // varchar(50)
		[Column("Tháng 9"),                                                 Nullable] public string Tháng9                                    { get; set; } // varchar(50)
		[Column("Tháng 10"),                                                Nullable] public string Tháng10                                   { get; set; } // varchar(50)
		[Column("Tháng 11"),                                                Nullable] public string Tháng11                                   { get; set; } // varchar(50)
		[Column("Tháng 12"),                                                Nullable] public string Tháng12                                   { get; set; } // varchar(50)
		[Column("Ghi chú"),                                                 Nullable] public string GhiChú                                    { get; set; } // varchar(50)
	}

	public static partial class TableExtensions
	{
		public static AuthorizeFile Find(this ITable<AuthorizeFile> table, string Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static AuthorizeToRole Find(this ITable<AuthorizeToRole> table, string Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static DashBoardUser Find(this ITable<DashBoardUser> table, string Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static FTTH Find(this ITable<FTTH> table, string Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static MasterFileKH2022 Find(this ITable<MasterFileKH2022> table, string Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static MasterVTCNTT Find(this ITable<MasterVTCNTT> table, string Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static NameTableExist Find(this ITable<NameTableExist> table, string Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static Report Find(this ITable<Report> table, string Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static ReportGroup Find(this ITable<ReportGroup> table, string Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static SelectTable Find(this ITable<SelectTable> table, string Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static StorageValue Find(this ITable<StorageValue> table, string Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static TypeValue Find(this ITable<TypeValue> table, string Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}
	}
}

#pragma warning restore 1591
