using VTQT.Web.Framework.Modelling;

namespace VTQT.SharedMvc.Dashboard.Models
{
    public class FTTHModel : BaseEntityModel
    {
        public string TuầnCậpNhật { get; set; } // varchar(50)
        public string Miền { get; set; } // varchar(50)
        public string TỉnhThành { get; set; } // varchar(50)
        public string Năm_hợpĐồng { get; set; } // varchar(50)
        public string TênDựÁn { get; set; } // varchar(50)
        public string TìnhTrạngHoạtĐộng { get; set; } // varchar(50)
        public string LoạiKháchHàng { get; set; } // varchar(50)
        public string KháchHàng { get; set; } // varchar(100)
        public string SốĐiệnThoại { get; set; } // varchar(150)
        public string ĐịaChỉ { get; set; } // varchar(150)
        public string MãKH_CID { get; set; } // varchar(50)
        public string SốHợpĐồng { get; set; } // varchar(100)
        public string CSPhụTrách { get; set; } // varchar(50)
        public string GóiCước { get; set; } // varchar(50)
        public string TrảTrước { get; set; } // varchar(50)
        public string SốThángĐượcTặngTrong1Năm { get; set; } // varchar(50)
        public string SốThángDùng { get; set; } // varchar(50)
        public string CướcHợpĐồngHàngTháng { get; set; } // varchar(50)
        public string CướcThángInternet { get; set; } // varchar(50)
        public string CướcThángTruyềnHình { get; set; } // varchar(50)
        public string TỷLệChiaSẻChoĐốiTácPhầnInternet { get; set; } // varchar(255)
        public string TỷLệChiaSẻChoĐốiTácPhầnTruyềnHình { get; set; } // varchar(50)
        public string CướcHTCĐượcNhậnHàngTháng { get; set; } // varchar(50)
        public string CướcHTCĐượcNhậnĐượcTBSauKhiTrừĐiKhuyếnMại { get; set; } // varchar(255)
        public string CướcĐãThuLần1 { get; set; } // varchar(50)
        public string ChủThểXuấtHóaĐơn { get; set; } // varchar(50)
        public string NgàyKýHĐ_LắpĐặt { get; set; } // varchar(50)
        public string NgàyNghiệmThu { get; set; } // varchar(50)
        public string NgàyHếtHạnTheoTerm12Tháng { get; set; } // varchar(50)
        public string NgàyThanhLý { get; set; } // varchar(50)
        public string ThanhLý_trướcHạnHaySauHạn_ { get; set; } // varchar(50)
        public string DoanhThuMấtĐiDoThanhLý_theoTermHĐ_ { get; set; } // varchar(50)
        public string ChiTiếtLýDoThanhLý { get; set; } // varchar(50)
        public string PhânLoạiThanhLý { get; set; } // varchar(50)
        public string Nền { get; set; } // varchar(50)
        public string GiảmNền { get; set; } // varchar(50)
        public string DoanhThuPhátTriểnMới { get; set; } // varchar(255)
        public string TổngDT { get; set; } // varchar(50)
        public string Tháng1 { get; set; } // varchar(50)
        public string Tháng2 { get; set; } // varchar(50)
        public string Tháng3 { get; set; } // varchar(50)
        public string Tháng4 { get; set; } // varchar(50)
        public string Tháng5 { get; set; } // varchar(50)
        public string Tháng6 { get; set; } // varchar(50)
        public string Tháng7 { get; set; } // varchar(50)
        public string Tháng8 { get; set; } // varchar(50)
        public string Tháng9 { get; set; } // varchar(50)
        public string Tháng10 { get; set; } // varchar(50)
        public string Tháng11 { get; set; } // varchar(50)
        public string Tháng12 { get; set; } // varchar(50)
        public string GhiChú { get; set; } // varchar(50)

    }
}